/**
 *This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.
 */
package com.mobile_live_widgets_prod.myjavaservice1.controller;

import com.mobile_live_widgets_prod.myjavaservice1.MyJavaService1;
import java.lang.String;
import javax.servlet.http.HttpServletRequest;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;

@RestController
@RequestMapping(value = "/myJavaService1")
public class MyJavaService1Controller {

    @Autowired
    private MyJavaService1 myJavaService1;

    @RequestMapping(value = "/sampleJavaOperation", produces = "application/json", method = RequestMethod.GET)
    public String sampleJavaOperation(@RequestParam(value = "name", required = false) String name, HttpServletRequest request) {
        return myJavaService1.sampleJavaOperation(name, request);
    }
}
