/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

import com.hrdb.models.procedure.*;

@Service
public class HrdbProcedureExecutorServiceImpl implements HrdbProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(HrdbProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("hrdbWMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;

    @Transactional(value = "hrdbTransactionManager")
    @Override
    public ProcDataResponse executeProc_data(Integer baddr, Integer bcount) {
        Map params = new HashMap(2);

        params.put("B_ADDR", baddr);
        params.put("B_COUNT", bcount);

        return procedureExecutor.executeNamedProcedure("Proc_data", params, ProcDataResponse.class);
    }

}


