/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.hrdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcDataResponse implements Serializable {


    @ColumnAlias("B_ADDR")
    private Integer baddr;

    public Integer getBaddr() {
        return this.baddr;
    }

    public void setBaddr(Integer baddr) {
        this.baddr = baddr;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcDataResponse)) return false;
        final ProcDataResponse procDataResponse = (ProcDataResponse) o;
        return Objects.equals(getBaddr(), procDataResponse.getBaddr());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBaddr());
    }
}